### ISSUE TITLE
Replacement of comments fails in text contains "//"

### ISSUE THREAD

**Issue by Thonarn** [rjray/json-withcomments#3]
It found this module useful when developing parsing of large JSON files, by only letting small parts of the files to get through.

But I experienced an error when a URL is present in a string.

The string was truncated after the colon, sample line:

   "short_description": "Documentation can be found at http://developer.abc.com/api/xyzapi.html.",
   
  Is changed to:
  
   "short_description": "Documentation can be found at http:

This seems that the line is truncated from and including any occurence of //

**Comment by rjray** [comment]
To be honest, I'm not really supporting this module anymore. I learned that the "regular" [CPAN JSON module](https://metacpan.org/dist/JSON) has a configuration setting called `relaxed` that handles this far better than I do. To be fair, it expects the comments to be shell-style/perl-style (starting with `#`), which may or may not fit your use case.
